# Assignment 12: Precision and recall, Boolean search, PageRank




This problem set consists of several different sections. Some of them involve coding, others require you to specify a number or string, and others are free response.

At the end of this lesson, you will be able to:


- Compute the precision and recall of a simple search or similar process
- Construct and execute simple Boolean searches on a given text
- Run the PageRank algorithm, modify its input, and evaluate the consequences on its output


While you work on the assignment, save early and often. If you get a "dead kernel" error, click on "Kernel", then "Restart".

In [1]:
#Preliminary: install and load nltk (Natural Language Toolkit)

!pip install nltk
import nltk 

nltk.download('punkt')


[nltk_data] Downloading package punkt to /home/ucloud/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


# 1. Precision and recall


*Look into what precision and recall mean [here](https://en.wikipedia.org/wiki/Precision_and_recall)* 

**Question 1.1** You have 100 books on your bookshelf, of which 60 are about cats and 40 are about dogs. You build a catalog for your little collection. Your friend uses this catalog to search your collection for books about cats. The catalog returns the titles of 50 of the books on your shelf. Of the 50 titles it returns, 40 are about cats and the rest are about dogs. What is the **precision** of your catalog in the case of this query? Give the result either as a fraction of integers or as a decimal number.

In [2]:
solution_q1_1 = 40/50
solution_q1_1

0.8

**Question 1.2** And what is the **recall** of your catalog in the case of this query? Give the result either as a fraction of integers or as a decimal number.

In [3]:
solution_q1_2 = 40/60
solution_q1_2

0.6666666666666666

# 2. Boolean search using five documents on Star Wars


### Making the corpus
Below you will find five brief "documents" (text snippets) on the Star Wars movies, taken from Wikipedia. Don't forget to run the code in each cell!

In [4]:
doc1 = "Frank Oz provided Yoda's voice with each film and spent his skills to be a puppeteer in the original trilogy and Star Wars Episode I: The Phantom Menace. For the latter, in some walking scenes, Warwick Davis incarnated Yoda as well. For the radio dramatizations of The Empire Strikes Back and Return of the Jedi, Yoda was voiced by John Lithgow, while Tom Kane voiced him in the Clone Wars animated series, several video games, and the new series Star Wars: The Clone Wars."

# We're going to store these documents in a dictionary, which makes them easier to work with:
documents = {'doc1':doc1}
print(doc1)

Frank Oz provided Yoda's voice with each film and spent his skills to be a puppeteer in the original trilogy and Star Wars Episode I: The Phantom Menace. For the latter, in some walking scenes, Warwick Davis incarnated Yoda as well. For the radio dramatizations of The Empire Strikes Back and Return of the Jedi, Yoda was voiced by John Lithgow, while Tom Kane voiced him in the Clone Wars animated series, several video games, and the new series Star Wars: The Clone Wars.


In [42]:
doc2 = "Luke Skywalker lives a humdrum existence on Tatooine with his Uncle Owen and Aunt Beru that have kept his father's true history a secret from him. He initially wants to join the Imperial Academy to become a pilot with his childhood friend Biggs Darklighter, but is held back by his uncle who ostensibly needs his help on the moisture farm (while it was to hopefully prevent Luke from following his father's path). He takes his first steps toward his destiny when he finds the two droids C-3PO and R2-D2. After delivering R2-D2's message to hermit Ben Kenobi, Ben tells Luke that his father was a Jedi and presents him with his father's lightsaber and then tells him that his father was murdered by a traitorous Jedi. Ben offers to take Luke to the planet Alderaan and train him in the ways of the Force, but Luke rejects his offer."

documents['doc2'] = doc2
print(doc2)

Luke Skywalker lives a humdrum existence on Tatooine with his Uncle Owen and Aunt Beru that have kept his father's true history a secret from him. He initially wants to join the Imperial Academy to become a pilot with his childhood friend Biggs Darklighter, but is held back by his uncle who ostensibly needs his help on the moisture farm (while it was to hopefully prevent Luke from following his father's path). He takes his first steps toward his destiny when he finds the two droids C-3PO and R2-D2. After delivering R2-D2's message to hermit Ben Kenobi, Ben tells Luke that his father was a Jedi and presents him with his father's lightsaber and then tells him that his father was murdered by a traitorous Jedi. Ben offers to take Luke to the planet Alderaan and train him in the ways of the Force, but Luke rejects his offer.


In [6]:
doc3 = "When the Empire attacks the Rebel base, Solo transports Chewbacca, along with Princess Leia and C-3PO to Cloud City where his old friend (and Cloud City administrator) Lando Calrissian operates to hide from Imperial agents. When bounty hunter Boba Fett tracks the Falcon to Cloud City, Darth Vader forces Calrissian to help capture Solo sealed in carbonite for delivery to Jabba the Hutt. But Lando frees Vader's other captives and they may rescue Solo but are too late as Fett escapes with Solo's frozen body."

documents['doc3'] = doc3
print(doc3)

When the Empire attacks the Rebel base, Solo transports Chewbacca, along with Princess Leia and C-3PO to Cloud City where his old friend (and Cloud City administrator) Lando Calrissian operates to hide from Imperial agents. When bounty hunter Boba Fett tracks the Falcon to Cloud City, Darth Vader forces Calrissian to help capture Solo sealed in carbonite for delivery to Jabba the Hutt. But Lando frees Vader's other captives and they may rescue Solo but are too late as Fett escapes with Solo's frozen body.


In [7]:
doc4 = "In her first appearance in Star Wars Episode IV: A New Hope, Princess Leia is introduced as the Princess of Alderaan and a member of the Imperial Senate. Darth Vader captures her on board the ship Tantive IV, where she is acting as a spy for the Rebel Alliance. He accuses her of being a traitor and demands to know the location of the secret technical plans of the Death Star, the Galactic Empire's most powerful weapon. Unknown to Vader, the young Senator has hidden the plans inside the Astromech droid R2-D2 and has sent it to find Jedi Master Obi-Wan Kenobi on the nearby planet of Tatooine."

documents['doc4'] = doc4
print(doc4)

In her first appearance in Star Wars Episode IV: A New Hope, Princess Leia is introduced as the Princess of Alderaan and a member of the Imperial Senate. Darth Vader captures her on board the ship Tantive IV, where she is acting as a spy for the Rebel Alliance. He accuses her of being a traitor and demands to know the location of the secret technical plans of the Death Star, the Galactic Empire's most powerful weapon. Unknown to Vader, the young Senator has hidden the plans inside the Astromech droid R2-D2 and has sent it to find Jedi Master Obi-Wan Kenobi on the nearby planet of Tatooine.


In [8]:
doc5 = "Three years later in Star Wars Episode V: The Empire Strikes Back, Lord Vader leads an Imperial starfleet in pursuit of the Rebels. Intent on turning Luke to the dark side, Vader captures Princess Leia, Han Solo, Chewbacca and C-3PO on Cloud City to use them as bait for Luke. During a lightsaber duel, Vader cuts off Luke's right hand and reveals that he is Luke's father"

documents['doc5'] = doc5
print(doc5)

Three years later in Star Wars Episode V: The Empire Strikes Back, Lord Vader leads an Imperial starfleet in pursuit of the Rebels. Intent on turning Luke to the dark side, Vader captures Princess Leia, Han Solo, Chewbacca and C-3PO on Cloud City to use them as bait for Luke. During a lightsaber duel, Vader cuts off Luke's right hand and reveals that he is Luke's father


In [9]:
# You can print the start of each document to make sure 
# that all 5 documents have been stored properly:
for doc in sorted(documents):
    print(f"\n {doc}: \n {documents[doc][0:50]} ...")


 doc1: 
 Frank Oz provided Yoda's voice with each film and  ...

 doc2: 
 Luke Skywalker lives a humdrum existence on Tatooi ...

 doc3: 
 When the Empire attacks the Rebel base, Solo trans ...

 doc4: 
 In her first appearance in Star Wars Episode IV: A ...

 doc5: 
 Three years later in Star Wars Episode V: The Empi ...


### Boolean serach
Boolean search looks for documents based on the presence or absence of specific search terms. The following cell defines a limited version of boolean search that you will use in subsequent cells. In those cells, you will call the function defined here by specifying a set of terms and whether the documents found should contain *all* or *any* of the terms, using the "and" and "or" operators, respectively.

In [10]:
# Please run the code in this cell without changing it - see code explanation below
import re
def boolean(comparison,terms,documents): # 1
    # invert dictionary
    documents_inverse = {value.lower():key for key,value in documents.items()} #2
    # if we got just one term (i.e., a string), make it into a list of one
    if type(terms)==str: # 3
        terms = [terms]
        
    relevant = []
    if comparison == "or": # 4
        for d in documents: # 5
            document = documents[d].lower()
            rel = False # 6
            for term in terms:
                # search using regular expression \b (word boundary) operator so we only match whole words
                if re.search(r"\b" + re.escape(term.lower()) + r"\b", document):
                    rel = True
            if rel == True:
                relevant.append(documents_inverse[document])
    if comparison == "and":
        for d in documents:
            document = documents[d].lower()
            rel = True
            for term in terms:
                # search using regular expression \b (word boundary) operator so we only match whole words
                if not re.search(r"\b" + re.escape(term.lower()) + r"\b", document):
                    rel = False
            if rel == True:
                relevant.append(documents_inverse[document])
    
    return relevant

#### Code Explanation - the in depth version 
_The following explanation refers to the above code block, referencing parts in parentheses, e.g. `(1)`._

(1) This line here, as we have seen before, defines a function called `boolean` that takes three arguments: `comparison`, `terms`, and `documents`. 

(2) This line goes ahead and inverts the dictionary `documents` that we pass into the function whenever we use it using something called list comprehension. It switches every key, value pair in the dictionary. This means that the text becomes the key, and the document name (doc1, doc2, doc3, doc4) becomes the value. 

`documents_inverse = {value.lower():key for key,value in documents.items()}` is the same as: <br>
        
        documents_inverse = {} 
        for key,value in documents.items():
            value = value.lower()
            documents_inverse[value] = key
            
The reason we make the inversed dictionary is so we can check which document name (doc1, doc2, doc3, doc4) that fits the text with the matched term(s). In other words, we go into the regular dictionary and find which texts contain the terms we are interested in and then we go into the inversed dictionary to fin the corresponding document name for that text. 

(3) As the comment above suggestions, we check to see if the variable `terms` is a string. If it is, we go ahead and convert it to a list. The reason we do this is because the code below acts as though `terms` is always a list. If we didn't change `terms` to a list here, then each loop below would check each _character_ of the string `terms`. A string is just a list of characters! Anyway, the takeaway is that, because the code below uses `terms` as if its a list, we want to make sure it's always a list.

(4) Here we have our two checks for `comparison` (well, the second one is below that checks if it equals `"and"`, but the blocks are rather similar). 

(5) The body of our if statement goes ahead and iterates through every document we've assigned above. It then uses regular expressions to find where each term shows up and appends- or adds- the document to a list called `relevant`. Then, when the function returns `relevant` as a list, we get a list of all the documents where our terms show up, depending on whether we use `"or"` or `"and"`. Nice! 

(6) Using a boolean statement like this is both useful and highlights how the "or" operator works differently from the "and" operator. Specifically, if the operator is "or", we start the search for any of the terms within a specific document by first setting rel to False. If we then find any of the terms in the document, we set it to True. Once checking for the terms is over, we check whether rel is True and if it is, we append the document name to our list of relevant documents. However, for the "and" operator, we kind of do the opposite. We start by assuming that the document will be relevant by setting relevant to True. When we then loop over the terms, if any of the terms is NOT in the document, we set rel to False, and the document will not be appended to our list of relevant terms. This means the document is diqualified from being relevant if it does not contain *all* of the terms we are searching for. 


#### How the function works in short
We give the function an operator ("and" or "or"), the terms we want to search for, and the dictionary of documents we wish to search in. We then check all the documents in the dictionary based on the operator we specified. If it was the "or" operator, we find the documents that contain any of the terms and return a list of those documents. We do this by finding the corresponding document name in our inverted dictionary for each text that was relevant. If it was the "and" operator, we find all the documents that contain all the terms we specified by excluding documents that do not have a term, and again make a list of those documents' name. 


The cell below explains how to particularly use this function.

You can do Boolean retrieval by calling the above function (called `boolean`). When calling the function, you need to give it three arguments:

* the operator ("and" or "or")
* a list of terms to search for (`["Term1","Term2"..."TermN"]`)
* the document collection to search through (in this case our dictionary called `documents`)

When only one term is searched for, it goes into a list by itself. In that case, it doesn't matter whether the operator is "and" or "or".

Try running the following example:

In [11]:
boolean("and", ["the", "force"], documents)

['doc2']

Convince yourself that the returned documents indeed contain the right query terms!


**Question 2.1** Using the Boolean retrieval model as implemented in the function `boolean`, construct a query that returns the set of documents that contain both the word "Darth" and the word "Vader".

In [12]:
solution_2_1 = boolean("and", ["Darth", "Vader"], documents)
# You can check your results by running this cell
print(solution_2_1)

['doc3', 'doc4']


**Question 2.2** Now construct a query that returns the set of documents that contain either the word "Darth" or the word "Vader" (or both).

In [13]:
solution_2_2 = boolean("or", ["Darth", "Vader"], documents)
# You can check your results by running this cell
print(solution_2_2)

['doc3', 'doc4', 'doc5']


**Question 2.3** Now construct a query that returns the set of documents that contain at least one of the following words: "Darth", "Vader", "Luke", "Skywalker".

In [14]:
solution_2_3 = boolean("or", ["Darth", "Vader", "Luke", "Skywalker"], documents)
# You can check your results by running this cell
print(solution_2_3)

['doc2', 'doc3', 'doc4', 'doc5']


# 3. Vectors
The  boolean  search  demonstrated  above  requires  exact  matches  and  returns  all  matching  documents.  Vector  space  models  instead  allow  partial  matching  and,  as  implemented  below,  allow  us  to  rank  the  returned  documents.  Informally,  this  model  generates  a  numeric  representation  of  each  document  and  the  query  and  computes  similarity  as  a  number  between  0  and  1.  A  document  with  a  low  score  contains  few  of  the  search  terms,  while  a  document  with  a  higher  score  contains  more  search  terms.  This  measure  of  similarity  also  normalizes  for  document  length  (accounts  for  differing  document  length  when  computing  scores).  Without  this  feature,  longer  documents  would  generally  score  higher  simply  because  they  contain  more  words  in  total.

[**You can read a super simple five-minute explanation of measuring text similarity here**](https://towardsdatascience.com/introduction-to-text-representation-and-similarity-b5dd3fd71737)


Let's look at an example:

**Sentence 1**: “Global warming is increasing”

**Sentence 2**: “There is increasing ocean temperature”



**STEP 1**: Let's pick only the most *informative* unique words from the two sentences.

Unique Words: global, warming, is, increasing, there, ocean, temperature <br>
Informative words: global, warming, increasing, ocean, temperature

**STEP 2**: Count the number of occurrences of unique words in each of the sentences

Analysis of sentence 1
```
global, 1
warming, 1
increasing, 1
ocean, 0
temperature, 0
```

Analysis of sentence 2
```
global, 0
warming, 0
increasing, 1
ocean, 1
temperature, 1

```

The easy part is over and before we proceed, you must know that NLP’s text similarity works on the basis of cosine similarity. *Cosine similarity* is basically the cosine of the angle between two vectors. So, we want to convert the sentences into two vectors, which we’ve already done!


**Vector of sentence 1:** [1,1,1,0,0]

**Vector of sentence 2:** [0,0,1,1,1]

Now let’s visualize the vectors.

Do note that, in our case we have a **5D** vector and because it’s not possible to visualize a 5D vector, let's just look at a **3D** vector, representing three words in our vector space. 

So, here we have two 3D vectors [ 1, 1, 1 ] and [ 0, 0, 1 ]. You can imagine these vectors as 2 sentences with 3 unique words in total. Here, [ 1, 1, 1 ] would mean that all 3 unique words occur once in the first sentence while [ 0, 0, 1 ] would mean that only the 3rd unique word occurs once in the second sentence.

![](https://miro.medium.com/v2/resize:fit:640/format:webp/1*zXJOIv1Ouxegi-rE30fKLg.png)

We’re interested only in the **angle** between these two vectors. The closer the two lines are, the smaller will be the angle and hence, similarity increases. So, If any two sentences are perfectly similar you’d see only one line in the 3D space, as the two lines would overlap each other.

![](https://miro.medium.com/v2/resize:fit:638/format:webp/1*ipF4GqzTxDGf1cZqIfglug.png)

![](https://miro.medium.com/v2/resize:fit:640/format:webp/1*4slYq804eanHw7pqzHh23w.png)

# Calculating cosine similarity 
Let's look at an example of how to calculate cosine similarity for two sentences given the vectors assigned to their terms. 

**Sentence 1**: “*Global warming* is *increasing*”

**Sentences 2**: “There is *increasing ocean temperature*”


**Vector of sentence 1:** [1,1,1,0,0]

**Vector of sentence 2:** [0,0,1,1,1]


Now we want to measure the angle between these two vectors. Here is the fomula for that: 

![](https://miro.medium.com/v2/resize:fit:350/format:webp/1*zpM7o4mYqK15J_zH9ifZpA.png)

In the numerator, we have the **dot product** of the vectors and in the denominator, we have the product of the lengths of the two vectors.


Let’s find out the **dot product** for our case:

The Formula -> (u1 * v1) + (u2 * v2) + ….. + (un * vn)

That’d be -> (1 * 0) + (1 * 0) + (1 * 1) + (0 * 1) + (0 * 1)

Now let's find the lengths: 

![](https://miro.medium.com/v2/resize:fit:640/format:webp/1*GEMt1G0_blmq-hUTkl-e2Q.png)

# Now we'll do it manually in Python 


In [15]:
#  Square  root  and  log  functions  needed  for  calculations:
from  math  import  sqrt,  log

In [16]:
#Get the dot product of the two vectors
(1*0) + (1*0) +(1*1) +(0*1) +(0*1) 

1

In [17]:
#Get the length of the two vectors and multiply them
sqrt(1**2+1**2+1**2+0**2+0**2)*sqrt(0**2+0**2+0**2+1**2+1**2)

2.4494897427831783

In [18]:
# Divide the dot product by the length of the two vectors
1/2.4494897427831783

0.40824829046386296

Now let's build a function to calculate cosine similarity for us without having to go through all these steps!

In [19]:
#  Dot  product  makes  things  a  lot  simpler  - rather than calculate this manually, we can load the dot package from numpy
from  numpy  import  dot

#We're going to treat the query itself as a vector to compute the dot product. Most terms from the docs aren't in the query, so we'll treat those as 0s!
#  cosine  similiarity:
def  cosine_sim(d,q):
    sim_un  =  dot(d,q)    
    norm  =  sqrt(dot(d,d))*sqrt(dot(q,q))+1e-16 # we need to add 0.0000000000000001 bc you can't divide by 0 (which we might get if none of the query words are in the doc)
    return round(sim_un/norm,3) #rounds the number within 3 decimal places


##### Brief code explanation
this function takes a document vector (d) and a query vector (q). it then calculates the cosine similarity between the two using the equation from earlier. 

Now what we want to do is define a function <code>doc_vectors</code> that will take a query (<code>terms</code>) and a set of documents (<code>docs</code>) as input and generate weight vectors for each document based on the frequency of the terms in those documents. **Don't worry about understanding everything here but give it a try. In depth explanation can be found in the solutions notebook.**

In [20]:
#  Generate  weight  vectors  for  each  document:
def  document_vectors(terms,docs):  
    terms  = [term.lower() for  term  in  terms] # 1 
    
    #  define  some  useful  values  used  repeatedly  in  calculations  (N  and  n  from  above):        
    N  =  len(docs) #number of documents       
    counts  =  [sum([1.0 for  d  in  docs  if  term  in docs[d]])  for  term  in  terms] # 2
    
    #  pre-calculate  the  scaling  term  for  each  weight:        
    scaling  =  [log(N/(n+1e-16),2)  for  n  in  counts] # 3
    #  instructions for calculating weight  vectors  for  each  document in sci. notation 
    # i.e., setting up the dictionary we will use for saving the weights 
    weights  =  {d:[1e-16]*len(terms)  for  d  in  docs} # 4
    
    #  actual  calculations - 5
    for  j  in  docs:                
        document  =  docs[j].lower().split()    
        for  i  in range(len(terms)):                       
            frequency  = document.count(terms[i])/float(len(terms))          
            weights[j][i]  =  frequency*scaling[i]
            
    #  return  weight  vectors:
    return  weights

##### Brief code explanation
this function takes a list of terms and a dictionary of documents and returns a dictionary that for every document gives the weighted frequency for every term (i.e., how many times is the term in the document scaled by how many times each term was in any of the docs). 

##### More specific
(1) makes every term lowercase by using a list comprehension. This is the same as:
            
            lower_terms = []
            for term in terms:
                lower_terms.append(term.lower())
                
notice I have to call my new list something else, bc otherwise I would have overwritten terms before I started looping. This is not necessary when using list comprehension - you can loop and overwrite at the same time. 

(2) this makes a list of how many times each term was in a document. The same as:

        counts = []
        
        for term in terms:
            term_count = [] # notice I make a new list for every term
            for d in docs: # for every document key (e.g, doc1) 
                if term in docs[d]: # if the term is in the text for that doc key
                    term_count.append(1.0) # term_count becomes a list of 1's (a 1 for every time the term was in a doc) 
                    
            counts.append(sum(term_count)) # Sum the list of numbers and add that sum to the counts list 
            
notice that counts will then comprise the sum of how many times each term was in a document which term_count saved. 

(3) this scaling term will be needed later. you don't need to understand the math, just the intuition. Basically, we take the total number of documents (N) and divide that by how many times a given term was in a document which we log scale. We then make a list where we save this scaling number for every term, which we will use later for finding the scaled frequency for that term. This list comprehension is the same as: 

    scaling = []
    
    for n in counts: # remember counts is a list of how many times each term was in a document
        term_scale = log(N/n+1e-16, 2) # we add 1e-16 bc you can't divide by zero, and 2 defines which log it should be
        
        scaling.append(term_scale)


(4) here, we get ready to save the weights for every document. We make a dictionary where the key is the document name (e.g., doc1), and the values is a list of 1e-16 that's the same length as the number of terms we have. why this is useful will become clear in the next section. For good measure, this list comprehension is the same as:

    weights = {}
    
    for d in docs:
        weights[d] = [1e-16] * len(terms)

if terms is 3 long for example, the value for every key would be [1e-16, 1e-16, 1e-16]

(5) now this loop is a fun one, this is what the rest of the function has been building up to. 

First, we loop over all the documents. For every document j (this is e.g., doc1), we first make the text for that doc lower case and split it, so it becomes a list of words (saved in document). We then loop over a range the same length as the number of terms (so for e.g., ['jedi, 'master'] the range would be from 0 up to but not including 2, i.e., 0 and 1).
So for the e.g., 0th term in the list of terms, we count how many times that term is in the list of words for this document, and divide this by the total number of terms, to get the frequency of that term in the document. We then scale this using the scaling factor we calculated in 3, and save this in our weights dictionary. The weights dictionary will then end up consisting of a key for every document, where the value for each key is a list where the scaled frequency of every term is saved in. 
It is totally okay if this does not make sense, let me know and I'll happily try to explain it differently. 

Now we need some code to return the results! We define another function <code>vector_query</code> which takes the same arguments (<code>terms, docs</code>) and uses <code>document_vectors</code> to return a single float between 0-1 representing the relevance of that doc given the query 

In [21]:
#  function  that  will  take  a  list  of  terms  and  documents  and return their cosine_sim score
def  vector_query(terms,docs):        
    vectors  =  document_vectors(terms,docs)
    similarities  =  {} # we're going to store our similarity scores here
    q  =  [1]*len(terms) #this is just returning a list of items (1s) equal to the number of terms in our query
    for  d  in  docs:
        similarities[d]  =  cosine_sim(vectors[d],q) #return similarity vectors for each term for each doc
    return  similarities

##### Brief code explanation
this function takes out list of terms and our dictionary of documents. it turns our documents into vectors using the functino above, and then finds the cosine similarity between each document vector (the scaled frequency for each term in the doc) and the vector our terms (which is just a list of 1's the same length as our list of terms). 
It then returns a dictionary with keys being the document names and the values being their cosine similarity to the query (list of terms). 

You  can  do  Vector  Space  retrieval  by  calling  the  above  function  (called  vector_query).  When  calling  the  function,  you  need  to  give  it  two  arguments:

-- a  list  of  search  terms  (["Term1","Term2"..."TermN"])

-- the  document  collection  to  search  through  (in  this  case  our  dictionary  called  documents)

You  can  either  type  the  seach  term  list  by  hand,  or  use  use  nltk's  
word_tokenize  method (which maps a string to a list of words). 

In  the  latter  case,  you  will  need  to  provide  the  query  as  a  single  string,  and  it  will  return  the  query  as  a  tokenized  list.

We'll try  running  the  following  example: "Jedi  master"

In [22]:
#  Import  the  "word_tokenize"  method:
from  nltk  import  word_tokenize

#  Specify  the  query  as  a  list  of  search  terms:
terms  =  word_tokenize("jedi master")

#  Do  vector  space  retrieval  on  the  search  query:
results  =  vector_query(terms,documents)

#  Print  a  ranked  list  of  results:
for  doc  in sorted(results, key=results.get, reverse=True):
    print(doc,  results[doc])

doc4 1.0
doc2 0.707
doc1 0.0
doc3 0.0
doc5 0.0


### Question 4

What just happened here?  What do these numbers represent?  Why does Doc4 get the highest number?

We got the cosine similarity between each document and the terms "jedi master". The numbers are how similar the vector containing the scaled frequency for each document is to the query vector. In human words, since doc4 has both jedi and master it gets the highest similarity of 1 because the doc contains every word of the query. Doc1 gets a pretty high score as well in spite of not conatining 'master' because it contains the word 'jedi'. Doc3 and doc5 do not contain any query words and therefore get 0. 

We can also see room for improvement in our function because doc1 gets 0 in spite of having the word 'jedi' because the comma makes it 'jedi,'. In the future we should therefore rrmember to remove punctuation. 

### Question 5


Consider  the  following  queries:

1."Luke,  I  am  your  father"

2."May  the  force  be  with  you"

Write  down  for  each  query  which  document  you  think  is  most  relevant for eahc query.  Simply  use  your  own  intuitions.


1) doc2 and doc5 since they both contain 'Luke' 'father'. 

2) they'll all be pretty equal

### Question 6

Use  the  Vector  Space  retrieval  model  to  determine  which  documents  are  relevant  for  each  query.  

Does  the  ranked  list  match  your  intuitions?  Why or why not?

In [24]:
# 1 
terms  =  word_tokenize("luke i am your father")

#  Do  vector  space  retrieval  on  the  search  query:
results  =  vector_query(terms,documents)
print(terms)

#  Print  a  ranked  list  of  results:
for  doc  in sorted(results, key=results.get, reverse=True):
    print(doc,  results[doc])
    
# 1.2 - adding the comma
terms  =  word_tokenize("luke, i am your father")

#  Do  vector  space  retrieval  on  the  search  query:
results  =  vector_query(terms,documents)
print(terms)

#  Print  a  ranked  list  of  results:
for  doc  in sorted(results, key=results.get, reverse=True):
    print(doc,  results[doc])
    
# 2
terms  =  word_tokenize("may the force be with you")

#  Do  vector  space  retrieval  on  the  search  query:
results  =  vector_query(terms,documents)

#  Print  a  ranked  list  of  results:
print(terms)
for  doc  in sorted(results, key=results.get, reverse=True):
    print(doc,  results[doc])

['luke', 'i', 'am', 'your', 'father']
doc5 0.458
doc2 0.451
doc1 0.0
doc3 0.0
doc4 0.0
['luke', ',', 'i', 'am', 'your', 'father']
doc5 0.418
doc2 0.412
doc1 0.0
doc3 0.0
doc4 0.0
['may', 'the', 'force', 'be', 'with', 'you']
doc3 0.563
doc1 0.408
doc2 0.408
doc4 0.0
doc5 0.0


for query 1 my intution was right. However, I'm surprised by query 2, but I guess 4 and 5 do not contain a whole lot of 'the' 'be' and 'with'

### Question 7

Would  the  removal  of  stop  words  in  the  query  improve  the  retrieval  results?  Come  up  with  a  list  of  words  to  remove  and  show  the  results  when  you  leave  out  these  words  from  the  query.

You can read more about stop-words on Wikipedia: https://en.wikipedia.org/wiki/Stop_words


In [32]:
# stop words
stop_words = ['the', 'is', 'be', 'i', 'your', 'will', 'am']

# function for removing them
def remove_stopwords(terms):
    terms = [term for term in terms if term not in stop_words]
    
    return terms

In [33]:
# same code but with added stop wrod removal
terms  =  word_tokenize("luke i am your father")
terms = remove_stopwords(terms)
#  Do  vector  space  retrieval  on  the  search  query:
results  =  vector_query(terms,documents)
print(terms)

#  Print  a  ranked  list  of  results:
for  doc  in sorted(results, key=results.get, reverse=True):
    print(doc,  results[doc])
    
# 1.2 - adding the comma
terms  =  word_tokenize("luke, i am your father")
terms = remove_stopwords(terms)

#  Do  vector  space  retrieval  on  the  search  query:
results  =  vector_query(terms,documents)
print(terms)

#  Print  a  ranked  list  of  results:
for  doc  in sorted(results, key=results.get, reverse=True):
    print(doc,  results[doc])
    
# 2
terms  =  word_tokenize("may the force be with you")
terms = remove_stopwords(terms)

#  Do  vector  space  retrieval  on  the  search  query:
results  =  vector_query(terms,documents)

#  Print  a  ranked  list  of  results:
print(terms)
for  doc  in sorted(results, key=results.get, reverse=True):
    print(doc,  results[doc])

['luke', 'father']
doc5 0.724
doc2 0.714
doc1 0.0
doc3 0.0
doc4 0.0
['luke', ',', 'father']
doc5 0.591
doc2 0.583
doc1 0.0
doc3 0.0
doc4 0.0
['may', 'force', 'with', 'you']
doc3 0.69
doc1 0.5
doc2 0.5
doc4 0.0
doc5 0.0


_Type your answer here, replacing this text._

### Question 8

Which  terms  would  you  need  to  add  to  doc2  to  make  it  the  highest  ranked  document  for  the  query  "May  the  force  be  with  you"?  Insert  terms  in  the  document  text  (you  should  re-define  it  in  the  cell  below  rather  than  altering  the  original  definition  above)  and  show  that these changes do make it the highest-ranked document for that query.

In [43]:
doc2  =  "may force " + documents['doc2'] # lazy solution haha

documents['doc2']  =  doc2

terms  =  word_tokenize("may the force be with you")

#  Do  vector  space  retrieval  on  the  search  query:
results  =  vector_query(terms,documents)

#  Print  a  ranked  list  of  results:
print(terms)
for  doc  in sorted(results, key=results.get, reverse=True):
    print(doc,  results[doc])

['may', 'the', 'force', 'be', 'with', 'you']
doc2 0.685
doc3 0.576
doc1 0.408
doc4 0.0
doc5 0.0


_Type your answer here, replacing this text._

### Question 9 (OPTIONAL!) 

Please write out in code OR pseudo-code a function to calculate the simplified tfidf of a word in a given document among a collection Docs. (Log optional.) For which doc among Docs does "Force" have the highest tf-idf?  What does that information mean?

_Type your answer here, replacing this text._


# 4. Word embeddings
In this part we'll explore: 
- What is a word embedding?
- What are the desired properties of word embeddings?
- What are the potential uses of word embeddings?




# Understanding word embeddings conceptually 

 [The Illustrated Word2Vec](https://jalammar.github.io/illustrated-word2vec/) uses color to illustrate how word embeddings work. The pre-trained Word2Vec embeddings are based on millions of documents.

![](http://jalammar.github.io/images/word2vec/word2vec.png)


# Please read the sections of [The Illustrated Word2Vec](https://jalammar.github.io/illustrated-word2vec/) called Word Embeddings and Analogies together with your group before proceeding! 









## Validation of Word Embeddings


In [45]:
!pip install text-preprocessing
!pip install gensim

import sys
import os
import gensim

from text_preprocessing import text_preprocessing


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 MB 1.6 MB/s eta 0:00:0000:0100:02
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 25.2 MB/s eta 0:00:00:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.2/103.2 kB 911.4 kB/s eta 0:00:0000:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 289.9/289.9 kB 7.2 MB/s eta 0:00:0000:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.5/26.5 MB 10.0 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.5/34.5 MB 18.5 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.8/56.8 kB 3.5 MB/s eta 0:00:00


[nltk_data] Downloading package omw-1.4 to /home/ucloud/nltk_data...


In [46]:
# example of preprocessing

text_data = "This is a sample text. We will need to split it into sentences. Afterwards, it will be split into tokens"

sentences = [sent.split() for sent in text_preprocessing.tokenize_sentence(text_data)]

In [47]:

# train a word embedding 
from gensim.models import Word2Vec
model = Word2Vec(sentences, 
                 vector_size=3, # size of the embedding layer (very low!)
                 window=5, # the size of the window (max distance between current and predicted word)
                 min_count=1, # ignore word with freq lower than this
                 sg = 1, # should it use skip-gram (alternative is CBOW)
                 workers=4) # number of cores to to use when training

# get the word vector for a given word in the sample text
print(model.wv["sample"])

[ 0.2692479  -0.19769652  0.00150541]


# Danish word embeddings

---
Now let's look at some of the examples you read about in The Illustrated Word2Vec in practice with Danish. There are a lot of examples in English online so below we work with Danish instead. 

(The Danish embeddings come from https://korpus.dsl.dk/resources/details/word2vec.html )



In [48]:
# this will take a minute or two
path = "/work/463910/compling23/HW12_material/danish_word2vec.bin"
model = gensim.models.KeyedVectors.load_word2vec_format(path, binary=True)

# English embeddings: http://vectors.nlpl.eu/repository/ (English CoNLL17 corpus)
# eng_path = '/work/463910/compling23/HW12_material/english/english_word2vec.bin'
# model = gensim.models.KeyedVectors.load(eng_path)

Let's first explore some synonyms 

In [49]:
# most similar word (synonym detection)
print("Aarhus = ")
print(model.most_similar(positive=['aarhus'], topn=10))

Aarhus = 
[('århus', 0.8463510870933533), ('arhus', 0.6873935461044312), ('påårhus', 0.6224691271781921), ('\xadårhus', 0.6112023591995239), ('aahus', 0.6039901375770569), ('aaarhus', 0.5978971123695374), ('aalborg', 0.5952222943305969), ('brabrand', 0.582003653049469), ('fuglesangs', 0.579281747341156), ('\xadaarhus', 0.5792354941368103)]


In [50]:
print("Kat = ")
print(model.most_similar(positive=['kat'], topn=10))


Kat = 
[('hund', 0.7446877956390381), ('katten', 0.6610313057899475), ('katte', 0.6483158469200134), ('undulat', 0.6468468308448792), ('kattekilling', 0.6416236758232117), ('hamster', 0.6367803812026978), ('huskat', 0.6367706656455994), ('granddanois', 0.6312282681465149), ('puddel', 0.6292955875396729), ('dalmatiner', 0.6285726428031921)]


In [51]:
print("is corona more associated with beer or a virus:")
print(model.similarity('corona', 'øl'))
print(model.similarity('corona', 'virus'))




is corona more associated with beer or a virus:
0.28827673
0.09207596


In [54]:
print(model.most_similar(positive=['mia'], topn=10)) #Try to run this code with YOUR name instead! 

#love having a name that's also an abbreviation haha

[('milliarder', 0.8217611312866211), ('mio', 0.7607602477073669), ('milliard', 0.7088867425918579), ('miakr', 0.6681352853775024), ('millarder', 0.6627052426338196), ('milliader', 0.658634603023529), ('mill', 0.6530202627182007), ('millioner', 0.6292245388031006), ('billioner', 0.6285216212272644), ('miokr', 0.6202195286750793)]


## Analogies

We can use basic arithmetic on word embeddings in order to conduct word analogy task.

For example:

```man is to king as woman is to queen```

So we can say that if we take the vector for ```king``` and subtract the vector for ```man```, we're removing the gender component from the ```king```. If we then add ```woman``` to the resulting vector, we should be left with a vector similar to ```queen```.

NB: It might not be _exactly_ the vector for ```queen```, but it should at least be _close_ to it.

```gensim``` has some quirky syntax that allows us to perform this kind of arithmetic.

Let's look at the following example: 

"Copenhagen is to Denmark what ___ is to England" 

or mathemathically: $CPH - DK + UK \approx $ ?

In [55]:
#capital
print(model.most_similar(positive=['københavn', 'england'], negative=['danmark'], topn=5))



[('london', 0.5973066091537476), ('glasgow', 0.5502803921699524), ('northampton', 0.5432627201080322), ('salford', 0.5406602621078491), ('ealing', 0.5345149040222168)]


In [56]:
# maybe not?
print(model.most_similar(positive=['københavn', 'tyrkiet'], negative=['danmark'], topn=5))


[('ankara', 0.6118887066841125), ('istanbul', 0.6096251010894775), ('izmir', 0.5366988182067871), ('tyrkiske', 0.5330621600151062), ('tyrkiets', 0.5058766007423401)]


In [57]:
# conjugations
print(model.most_similar(positive=['læge', 'manden'], negative=['mand'], topn=5))


[('lægen', 0.6586465239524841), ('speciallægen', 0.5684356689453125), ('rygspecialist', 0.5345785617828369), ('hjertelæge', 0.5298790335655212), ('praktiserende', 0.5248790383338928)]


In [58]:
print(model.most_similar(positive=['mand'], negative=['kvinde'], topn=5))

[('kavalerister', 0.30755141377449036), ('stab', 0.295112282037735), ('eskadron', 0.29292717576026917), ('armékorps', 0.2862314283847809), ('eskadroner', 0.27928563952445984)]


In [59]:
# play around with it :) 




## Odd-one-out Detection
This works by:
- take the mean of all the word-embeddings
- calculate the cosine-distance (similarity) from that center to each word
- return the most dissimilar word (i.e. the one with the highest cosine-distance from that mean vector)


In [60]:
model.doesnt_match("sodavand brød vin juice".split())


'brød'


Now change the code above to try some different words for odd-one-out detection. 


In [88]:
# your code here 
model.doesnt_match("glas vase vin karafel".split())


'vase'


## Other ways word embeddings have been used

shift in word meaning over time
![](https://ruder.io/content/images/size/w2000/2017/10/semantic_change.png)

Cross lingual word embeddings:
![](https://s3.ap-south-1.amazonaws.com/techleerimages/771a4957-7fb8-4ddd-ba04-4fa73187e5f1.png)

# Exercises:
These exercises are made for the Danish word embedding but feel free to use the English embeddings instead (ask Mia for help if you want to use the English). 



## Vector analogies 

- What is to woman ("kvinde") what man ("mand") to doctor ("læge")? Is this problematic?
- Write code to do this analogy instead: Paris - France + Italy. 
  - What is the expected result based on your own knowledge? What does Word2Vec produce? 

- Come up with one or two other analogies to try.





In [63]:
# doctor - man + woman
print(model.most_similar(positive=['læge', 'kvinde'], negative=['mand'], topn=5))



[('sygeplejerske', 0.6121259927749634), ('jordemoder', 0.6090441346168518), ('gynækolog', 0.6052830219268799), ('lægen', 0.5922764539718628), ('psykiater', 0.5645801424980164)]


In [70]:
# word - analogy <-- analogy embedding (then word + analogy embedding => analogy)
# write your own here
print(model.most_similar(positive=['god', 'engel'], negative=['ond'], topn=5))


[('fin', 0.4201897382736206), ('ditlev', 0.3924867510795593), ('vestastopchef', 0.37698087096214294), ('völkers', 0.3600253760814667), ('vestaschef', 0.3593840003013611)]


In [72]:
# word - analogy <-- analogy embedding (then word + analogy embedding => analogy)
# write your own here
print(model.most_similar(positive=['pilot', 'kvinde'], negative=['mand'], topn=5))


[('stewardesse', 0.5571776032447815), ('jagerpilot', 0.5140992403030396), ('faldskærmsudspringer', 0.49316951632499695), ('kamppilot', 0.47573158144950867), ('piloten', 0.47546449303627014)]


## Plurals and sentiment 
- Discuss how you would find plurals of a Danish word
    - Find plurals of 3 danish words using word embeddings
- Discuss how you would find the antonym of a Danish word
- Examine 3 words with multiple meaning, how well does word embeddings handle these?
- Load this tagged [data](https://github.com/fnielsen/afinn/blob/master/afinn/data/AFINN-da-32.txt) (code provided). This is from a Danish sentiment lexicon from AFINN tagged by Finn A. Nielsen (A Danish NLP researcher). Discuss how you could expand this lexicon using word embeddings and test out if your assumptions are correct.
- Can you use odd one out detection on AFINN's sentiment lexicon to check for errors in the dictionary? I.e. words which are tagged as positive but are in fact not?




In [62]:
# plural - singular <-- pluralis embedding 
print(model.most_similar(positive=['kvinder', 'kop'], negative=['kvinde'], topn=5))


print(model.most_similar(positive=['kopper', 'mand'], negative=['kop'], topn=5))


[('kaffe', 0.6035653948783875), ('te', 0.5248898267745972), ('kaffen', 0.4882567226886749), ('espresso', 0.4867384731769562), ('kage', 0.45227736234664917)]
[('kvinde', 0.4439041316509247), ('mænd', 0.42003360390663147), ('nazisoldater', 0.39018377661705017), ('mennesker', 0.38475483655929565), ('mands', 0.38311588764190674)]


In [69]:
# antonym, doesn't work great haha

print(model.most_similar(positive=['glad', 'mørkt'], negative=['sur'], topn=5))


[('dejligt', 0.45962202548980713), ('halvmørkt', 0.4467766284942627), ('bælgragende', 0.4454246759414673), ('mørke', 0.44052305817604065), ('bælgravende', 0.4374397099018097)]


In [74]:
# multiple meanings
print(model.most_similar(positive=['blade'], topn=5))

print(model.most_similar(positive=['lyst'], topn=5))

print(model.most_similar(positive=['bakken'], topn=5))

[('bladene', 0.7726895213127136), ('grundstillede', 0.6779847741127014), ('stængler', 0.675053060054779), ('trekoblede', 0.6741914749145508), ('håndfligede', 0.6717219948768616)]
[('lysten', 0.6161541938781738), ('trang', 0.5867336988449097), ('haftlyst', 0.5356452465057373), ('ubændig', 0.5343653559684753), ('hafttid', 0.5201312899589539)]
[('bears', 0.7627429366111755), ('bakkens', 0.6287217736244202), ('rabbits', 0.6193805932998657), ('bearsnæstved', 0.5866698622703552), ('bearsspiller', 0.5809119343757629)]


In [76]:
# loading data
import csv

path = '/work/463910/compling23/HW12_material/AFINN-da-32.txt'
with open(path) as f:
    reader = csv.reader(f, delimiter="\t")
    afinn = dict(reader)
    
afinn

{'absorberet': '1',
 'acceptere': '1',
 'accepterede': '1',
 'accepterer': '1',
 'accepteres': '1',
 'accepteret': '1',
 'advare': '-2',
 'advarede': '-2',
 'advarer': '-2',
 'advaret': '-2',
 'advarsel': '-3',
 'advarsler': '-3',
 'advarslerne': '-3',
 'afbrudt': '-2',
 'afbryde': '-2',
 'afbrydelse': '-2',
 'afbrydelser': '-2',
 'afbrydelserne': '-2',
 'afbryder': '-2',
 'affald': '-1',
 'afgift': '-1',
 'afgifter': '-1',
 'afgørende': '1',
 'afhængig': '-1',
 'afhængige': '-1',
 'afklaring': '2',
 'aflivning': '-1',
 'aflivningen': '-1',
 'aflivninger': '-1',
 'aflivningerne': '-1',
 'aflyse': '-2',
 'aflyser': '-2',
 'aflyses': '-2',
 'aflyst': '-2',
 'aflyste': '-2',
 'aflystes': '-2',
 'afskedige': '-1',
 'afskediges': '-2',
 'afskediget': '-2',
 'afsky': '-3',
 'afskyede': '-3',
 'afskyelig': '-3',
 'afskyelige': '-3',
 'afskyeligt': '-3',
 'afskyet': '-3',
 'afskyr': '-3',
 'afslappende': '2',
 'afslappet': '2',
 'afsløre': '-2',
 'afslører': '-2',
 'afsmitning': '-1',
 'afspor

In [93]:
positive = []
negative = []

for key,value in afinn.items():
    if int(value) > 0:
        positive.append(key)
    elif int(value) < 0:
        negative.append(key)

        
print(positive[:20])
print(negative[:20])

print(model.doesnt_match(positive))
print(model.doesnt_match(negative))


['absorberet', 'acceptere', 'accepterede', 'accepterer', 'accepteres', 'accepteret', 'afgørende', 'afklaring', 'afslappende', 'afslappet', 'afspænding', 'aftale', 'aftalt', 'afværge', 'afværges', 'agte', 'agtet', 'aktiv', 'aktiver', 'ambitiøs']
['advare', 'advarede', 'advarer', 'advaret', 'advarsel', 'advarsler', 'advarslerne', 'afbrudt', 'afbryde', 'afbrydelse', 'afbrydelser', 'afbrydelserne', 'afbryder', 'affald', 'afgift', 'afgifter', 'afhængig', 'afhængige', 'aflivning', 'aflivningen']
superior
boring


# 5. PageRank


Based on a gist by Sebastien Bratieres and on the Wikipedia page for PageRank.

PageRank was the website sorting algorithm that cemented Google's early success in the 1990s, when it displayed webpages with the highest PageRank first. Larry Page and Sergey Brin, the co-founders of Google, developed PageRank while they were PhD students at Stanford University in 1996 as part of a research project. PageRank is named both after Larry Page and after the term "web page". Its main idea is that important webpages are likely to receive many links from other important webpages. The PageRank algorithm can be seen as computing the probability that a person who randomly clicks on links and follows them will arrive at a particular website.  (In case you're wondering if this assumes that people keep clicking around, PageRank actually includes a dampening factor that represents the probability that a person will actually keep clicking as opposed to stopping where they are. It’s usually set to 0.85.)

It used to be the case that developers could see their page's PageRank via a tool that Google provided. Although this public score has since then been discontinued, PageRank is [still a part of Google's algorithm](https://ahrefs.com/blog/google-pagerank/).

Incoming links lift a website's rank if they come from higher-ranked sites, particularly if these sites have few outgoing links. The following slightly creepy graphic shows this. The higher a website's rank (as indicated by the number of size of websites pointing at it), the bigger it is and the bigger its smile is.

![PageRank cartoon](https://upload.wikimedia.org/wikipedia/commons/6/69/PageRank-hi-res.png)

_(Graphic by Felipe Micaroni Lalli, distributed under a [CC BY-SA 2.5](https://creativecommons.org/licenses/by-sa/2.5/deed.en) license. Source: https://upload.wikimedia.org/wikipedia/commons/6/69/PageRank-hi-res.png)_

Here we will work with a toy example that involves just eleven websites, which link to each other as shown here. In the graph below, the percentages and the sizes of the circles represent the page ranks of these sites. Let's look at an implementation of the PageRank algorithm.

![PageRank illustration](http://upload.wikimedia.org/wikipedia/commons/f/fb/PageRanks-Example.svg)

_(Graphic by 345Kai, placed into the public domain. Source: http://upload.wikimedia.org/wikipedia/commons/f/fb/PageRanks-Example.svg)_

First, we will encode the links present on this graph as a count matrix `M_counts`.

In [78]:
### THIS CELL DEFINES THE GRAPH ABOVE - DO NOT EDIT THIS CELL
import numpy as np
n_pages = 11 # numbering pages A through K as 0 to 10
M_counts = np.zeros((n_pages, n_pages)) # will hold the number of link counts (assumed 0 or 1)
# columns = starting page, row = destination page, ie M_ij = whether or not there is a link from j to i

# create variable names for each page index for clarity
# 1
pageA = 0
pageB = 1
pageC = 2
pageD = 3
pageE = 4
pageF = 5
pageG = 6
pageH = 7
pageI = 8
pageJ = 9
pageK = 10

# 2
M_counts[:,pageA] = 1 # page 0 (A in the graphic) is a sink because it has no outgoing links at all; 
# however, M cannot contain an all-zero column, so do as if A was linking to all other pages (ie put 1's everywhere)
M_counts[pageA,pageD] = 1  # to A from D
M_counts[pageB,pageC] = 1  # to B from C
M_counts[pageB,pageD] = 1  # to B from D
M_counts[pageB,pageE] = 1  # to B from E
M_counts[pageB,pageF] = 1  # to B from F
M_counts[pageB,pageG] = 1  # to B from G
M_counts[pageB,pageH] = 1  # to B from H
M_counts[pageB,pageI] = 1  # to B from I
M_counts[pageC,pageB] = 1  # to C from B
M_counts[pageD,pageE] = 1  # to D from E
M_counts[pageE,pageF] = 1  # to E from F
M_counts[pageE,pageG] = 1  # to E from G
M_counts[pageE,pageH] = 1  # to E from H
M_counts[pageE,pageI] = 1  # to E from I
M_counts[pageE,pageJ] = 1  # to E from J
M_counts[pageE,pageK] = 1  # to E from K
M_counts[pageF,pageE] = 1  # to F from E

print(M_counts)

[[1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### Code Explanation
_The following explanation refers to the above code block, referencing parts in parentheses, e.g. `(1)`._

(1) First, we go ahead and make a bunch of variables for each page set to numbers. This is mostly for code readability. Much clearer to say `pageA` links to `pageD` with the line `M_counts[pageA,pageD]` than it is to write something like `M_counts[0,3]`!

(2) Then we go ahead and initialize values for what pages are linked to each other. In the grid that prints out below, anywhere there's a `1` represents where a page is linked. The first column is all `1s` because each page will link back to A by default. Somewhere like `[1,3]` will be a 1 to represent page 1 linked to page 3- or as defined above, pageB linked to pageD!

Now we convert  `M_counts` to `M` below, by dividing each column by its sum, i.e. we are making sure columns sum to 1. 

In [79]:
M = np.empty((n_pages, n_pages))
for j in range(n_pages):
    M[:,j] = M_counts[:,j] / M_counts[:,j].sum()
np.set_printoptions(precision=3)
print(M)

[[0.091 0.    0.    0.5   0.    0.    0.    0.    0.    0.    0.   ]
 [0.091 0.    1.    0.5   0.333 0.5   0.5   0.5   0.5   0.    0.   ]
 [0.091 1.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.091 0.    0.    0.    0.333 0.    0.    0.    0.    0.    0.   ]
 [0.091 0.    0.    0.    0.    0.5   0.5   0.5   0.5   1.    1.   ]
 [0.091 0.    0.    0.    0.333 0.    0.    0.    0.    0.    0.   ]
 [0.091 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.091 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.091 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.091 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.091 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]]


The following code checks that `M` has the right format to be used by the PageRank.

In [80]:
def check_M(M):
    """
    check that M has the right format to be used by pagerank function
    """
    n_pages = M.shape[0] # n_pages is the number of rows of M
    np.testing.assert_equal(M.shape[0], M.shape[1], err_msg = 'M should be square')
    np.testing.assert_array_almost_equal(M.sum(axis=0), np.ones((n_pages)), 
                                         err_msg = 'assert each column sums to one (M is assumed column-stochastic)')
    for j in range(n_pages):
        M_column = M[:,j]
        n_nonzero = np.count_nonzero(M[:,j])
        np.testing.assert_array_almost_equal(M_column[M_column.nonzero()], np.ones((n_nonzero)) / n_nonzero,
                                             err_msg = 'in column %g, all non-zero entries should be equal (and equal to 1 divided by their number)' % j)

check_M(M) # will produce error if M does not have the right format

#### Code Explanation
_The following explanation refers to the above code block._

This code block uses the library `numpy`, as imported in a cell way above with `import numpy as np`. Where you see `np.testing.assert...` represents the numpy library making sure something is true. For example, the line below `n_pages = M.shape[0]` is testing if the first argument is equal to the second argument. Namely, if the shape (or dimensions) is a square. `M.shape[0]` gets the number of rows, and `M.shape[1]` gets the number of columns.

If you're curious, print out `M.shape`. You should see something like `(x,y)`. Thus, `M.shape[0]` would print the same value as `x`, and similarly for `M.shape[1]` and `y`.

We are now ready to apply the pagerank function, which will iteratively apply page transitions to an randomly initialized distribution over the pages, until we converge. The details of the PageRank algorithm do not matter for this exercise beyond what was described in the textbook; however, if you are interested, the [Wikipedia page on PageRank](https://en.wikipedia.org/wiki/PageRank) gives a good overview.

In [81]:
def pagerank(M, d=0.85, square_error=1e-8):
    """
    M : the adjacency matrix of the pages. It is assumed to be column-stochastic (i.e. column sum to 1); all links have equal weight.
    A page with no outgoing links (sink) is represented as a page with outgoing links to each other page (ie restart page).
    d: damping factor (this is not in the textbook, but commonly applied in PageRank implementations; it represents the probability that a user stops clicking)
    square_error : the algorithm iterates until the difference between two successive PageRank vectors v is less than this (in squared norm)
    returns the PageRanks of all pages
    """
    n_pages = M.shape[0] # n_pages is the number of rows of M
    v = np.random.rand(n_pages) # initialize to random vector
    v = v / v.sum() # make v sum to 1
    last_v = np.ones((n_pages)) # will contain the previous v
    M_hat = d * M + (1-d)/n_pages * np.ones((n_pages, n_pages)) # this is the central PageRank equation
    while np.square(v - last_v).sum() > square_error:
        last_v = v
        v = M_hat.dot(v) # at each iteration, progress one timestep
    return v

In [82]:
result = pagerank(M)
print("Result of running PageRank on M:")
site_names = "ABCDEFGHIJK"
for i in range(10):
    print("Page", site_names[i]+":", "{:.1%}".format(result[i]))

Result of running PageRank on M:
Page A: 3.3%
Page B: 38.4%
Page C: 34.3%
Page D: 3.9%
Page E: 8.1%
Page F: 3.9%
Page G: 1.6%
Page H: 1.6%
Page I: 1.6%
Page J: 1.6%


#### Code Explanation
_The following explanation refers to the above code blocks._

The first block, that defines our `pagerank` function, returns a list that is the pagerank of all pages- which you can see as the variable `result` in our second codeblock. The math tricks in the first block aside, the `pagerank` function gives you a list which is then printed in the second block. The higher the percentage, the more relevant they are when you search up something related to these websites (or pages).

These are the numbers (within the allowed error) displayed on the graph (the numbers on the graph are rounded exact values). There might be slight discrepancies because of how the algorithm depends on random numbers.

Suppose the webmaster of website B edits it to include a link to website A (so, B is now linking to both A and C). Look at the graphic above. Which site do you think will now have the highest PageRank? Will A continue to be ranked below C? (No need to submit an answer at this point, just keep the answer in mind.)

The following code is an exact copy of the code above, except that the variables have been renamend (instead of M_counts there is M_new_counts etc.), and in the first cell there are instructions to add a new link to A coming from website B. Add this link (<font color="red">remember, it is a link **to** A **from** B, not the other way around; note that in the code, all links are given in the format "to X from Y"; that is, it is counter to what people might normally intuit</font>). Then run that cell and all of the subsequent cells in preparation for the questions below.

In [83]:
### DUPLICATE OF CODE ABOVE -- EDIT THIS CELL AS INDICATED BELOW
import numpy as np
n_pages = 11 # numbering pages A through K as 0 to 10
M_new_counts = np.zeros((n_pages, n_pages)) # will hold the number of link counts (assumed 0 or 1)
# columns = starting page, row = destination page, ie M_ij = whether or not there is a link from j to i

# crate variable names for each page index for clarity
pageA = 0
pageB = 1
pageC = 2
pageD = 3
pageE = 4
pageF = 5
pageG = 6
pageH = 7
pageI = 8
pageJ = 9
pageK = 10

M_new_counts[:,pageA] = 1 # page 0 (A in the graphic) is a sink because it has no outgoing links at all; 
# however, M cannot contain an all-zero column, so do as if A was linking to all other pages (ie put 1's everywhere)
M_new_counts[pageA,pageD] = 1  # to A from D
M_new_counts[pageB,pageC] = 1  # to B from C
M_new_counts[pageB,pageD] = 1  # to B from D
M_new_counts[pageB,pageE] = 1  # to B from E
M_new_counts[pageB,pageF] = 1  # to B from F
M_new_counts[pageB,pageG] = 1  # to B from G
M_new_counts[pageB,pageH] = 1  # to B from H
M_new_counts[pageB,pageI] = 1  # to B from I
M_new_counts[pageC,pageB] = 1  # to C from B
M_new_counts[pageD,pageE] = 1  # to D from E
M_new_counts[pageE,pageF] = 1  # to E from F
M_new_counts[pageE,pageG] = 1  # to E from G
M_new_counts[pageE,pageH] = 1  # to E from H
M_new_counts[pageE,pageI] = 1  # to E from I
M_new_counts[pageE,pageJ] = 1  # to E from J
M_new_counts[pageE,pageK] = 1  # to E from K
M_new_counts[pageF,pageE] = 1  # to F from E
### YOUR TASK: ADD A LINE TO THE ABOVE LIST THAT REPRESENTS A NEW LINK TO PAGE A FROM PAGE B

print(M_new_counts)

[[1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [84]:
### DUPLICATE OF CODE ABOVE, BUT WITH M_new instead of M and M_new_counts instead of M_counts
M_new = np.empty((n_pages, n_pages))
for j in range(n_pages):
    M_new[:,j] = M_new_counts[:,j] / M_new_counts[:,j].sum()
np.set_printoptions(precision=3)
print(M_new)

[[0.091 0.    0.    0.5   0.    0.    0.    0.    0.    0.    0.   ]
 [0.091 0.    1.    0.5   0.333 0.5   0.5   0.5   0.5   0.    0.   ]
 [0.091 1.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.091 0.    0.    0.    0.333 0.    0.    0.    0.    0.    0.   ]
 [0.091 0.    0.    0.    0.    0.5   0.5   0.5   0.5   1.    1.   ]
 [0.091 0.    0.    0.    0.333 0.    0.    0.    0.    0.    0.   ]
 [0.091 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.091 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.091 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.091 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.091 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]]


In [85]:
### DUPLICATE OF CODE ABOVE, BUT WITH M_new instead of M and result_new instead of result
result_new = pagerank(M_new)
print("Result of running PageRank on M_new:")
site_names = "ABCDEFGHIJK"
for i in range(10):
    print("Page", site_names[i]+":", "{:.1%}".format(result_new[i]))

Result of running PageRank on M_new:
Page A: 3.3%
Page B: 38.4%
Page C: 34.3%
Page D: 3.9%
Page E: 8.1%
Page F: 3.9%
Page G: 1.6%
Page H: 1.6%
Page I: 1.6%
Page J: 1.6%


For this and the following questions, check the result against your intuitions before you submit. 

**Question 3.1** What is the percentage value of the top ranked website? Give the result as a decimal number between 1 and 100, rounded to one decimal, without the "percent" sign. Do not divide by 100. This question and the next one can be answered by checking the lists in the output above. It is there for us to see whether you have run the PageRank algorithm correctly as per our instructions.

In [ ]:
solution_3_1 = ...

**Question 3.2 (10 points)** And what is the percentage value of the second highest ranked website? Give the result as a decimal number between 1 and 100, rounded to one decimal, without the "percent" sign. Do not divide by 100.

In [ ]:
solution_3_2 = ...

## Background on search engine crawlers
Search engines "crawl" (i.e. look through) the web every few days or weeks and use the result to compute PageRank and similar measures. When you search for a term, the search engine returns sites ranked according to the index it has stored at that moment in time, which may be out of date in case there has been a change to some website. The following scenario tests your ability to understand the concept of crawling and to integrate this information with what you have just learned from practicing with the PageRank algorithm. 
- Suppose the index of a search engine is initially as above, before you made the change. Assume that the websites A, C, E, and F mention the search term "skiing" and that no other websites do. 
- On Tuesday, Alice, the webmaster of B, adds a link to A to her site as described above. The search engine does not know of this change yet. 
- On Wednesday, Bob searches for "skiing". 
- On Thursday, the search engine crawler visits Alice's website for the first time this week, and stores an updated index that reflects the change Alice has made to her website. The search engine then reruns PageRank as described above. 
- On Friday, Carol searches for "skiing".

<!-- BEGIN QUESTION -->

**Question 3.3.1**. What is the top result of Bob's search for the term "skiing"? In other words, which of sites A, C, E, and F (that is, which of those sites that mention the term) is ranked highest according to the index on Wednesday? Please state your answer as a single uppercase letter.

_Type your answer here, replacing this text._

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

**Question 3.3.2**. Briefly explain your reasoning. Why is the top result for Bob what you said it is?

_Type your answer here, replacing this text._

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

**Question 3.3.3**. What is the top result of Carol's search for the term "skiing"? In other words, which of sites A, C, E, and F (that is, which of those sites that mention the term) is ranked highest according to the index on Friday? Please state your answer as a single uppercase letter.

_Type your answer here, replacing this text._

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

**Question 3.3.4**. Briefly explain your reasoning. Why is the top result for Carol what you said it is?

_Type your answer here, replacing this text._